### ISSUE TITLE
Register Search URLs

### ISSUE THREAD

**Issue by ristes** [draganbozhinoski/ClientsAdministration#1]
The goal here is to have an entity:
```
@Entity
class CompanyDataSearch {
    @Id
    private String name;  // example: Validator
    private String urlPattern; // example https://validator.schema.org/#url=${text}
    
}
```

We should enable crud operations for this entity. 

On the CompanyEdit page, we should inject links for all of these entities as follows: 
`<a th:href="${companyDataSearch.urlPattern.replace("${text}", company.name)}" th:text="${companyDataSearch.name}"/>`

On the click of each of these links, it would be nice to show the content in `iframe` if possible. If not, in the first version we should display the result page in new tab.

**Comment by draganbozhinoski** [comment]
Done in the most recent commit.
